=== edgaros24/1PraktinisDarbas/untitled6/generated.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="owner">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="id" type="xs:unsignedByte" />
        <xs:element name="name" type="xs:string" />
        <xs:element name="lastname" type="xs:string" />
        <xs:element name="specialist">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="id" type="xs:unsignedByte" />
              <xs:element name="name" type="xs:string" />
              <xs:element name="lastname" type="xs:string" />
              <xs:element name="specialization" type="xs:string" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="animals">
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" name="animal">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="id" type="xs:unsignedByte" />
                    <xs:element name="name" type="xs:string" />
                    <xs:element name="gender" type="xs:string" />
                    <xs:element name="type" type="xs:string" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== edgaros24/1PraktinisDarbas/untitled6/generated.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<owner xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="generated.xsd">
    <id>17</id>
    <name>Ona</name>
    <lastname>Onute</lastname>
    <specialist>
        <id>18</id>
        <name>Vardenis</name>
        <lastname>Pavardenis</lastname>
        <specialization>Chirurgas</specialization>
    </specialist>
    <animals>
        <animal>
            <id>19</id>
            <name>Tom</name>
            <gender>Male</gender>
            <type>Cat</type>
        </animal>
        <animal>
            <id>20</id>
            <name>Mary</name>
            <gender>Female</gender>
            <type>Cat</type>
        </animal>
    </animals>
</owner>
